export const timezoneOptions = [
  { label: 'EST', value: 'EST' },
  { label: 'PST', value: 'PST' },
  { label: 'CST', value: 'CST' },
  { label: 'MST', value: 'MST' },
  { label: 'AST', value: 'AST' },
  { label: 'HST', value: 'HST' },
];

export const spcialitityOptions = [
  { label: 'Multi-Speciality', value: 'Multi-Speciality' },
  { label: 'Primary Care', value: 'Primary Care' },
  { label: 'Urgent Care', value: 'Urgent Care' },
  { label: 'Physical Therapy', value: 'Physical Therapy' },
  {
    label: 'Behavioral Health & Psychiatry',
    value: 'Behavioral Health & Psychiatry',
  },
  { label: 'Ophthalmology', value: 'Ophthalmology' },
  { label: 'Orthopedics', value: 'Orthopedics' },
  { label: 'Internal Medicine', value: 'Internal Medicine' },
  { label: 'Pediatrics', value: 'Pediatrics' },
  { label: 'Cardiology', value: 'Cardiology' },
  { label: 'Chiropractic', value: 'Chiropractic' },
  { label: 'Gastroenterology', value: 'Gastroenterology' },
  { label: 'Neurology', value: 'Neurology' },
  { label: 'Dermatology', value: 'Dermatology' },
  { label: 'Oncology', value: 'Oncology' },
  { label: 'Gynecology', value: 'Gynecology' },
  { label: 'Pain Management', value: 'Pain Management' },
  { label: 'Podiatry', value: 'Podiatry' },
  { label: 'Urology', value: 'Urology' },
];

// export const PROVIDER_TYPE_OPTIONS = [
//   { label: 'MD', value: 'MD' },
//   { label: 'RN', value: 'RN' },
//   { label: 'DO', value: 'DO' },
//   { label: 'LPN', value: 'LPN' },
//   { label: 'APRN', value: 'APRN' },
//   { label: 'NP', value: 'NP' },
//   { label: 'PA', value: 'PA' },
//   { label: 'PT', value: 'PT' },
//   { label: 'OT', value: 'OT' },
//   { label: 'PSYD', value: 'PSYD' },
//   { label: 'LCSW', value: 'LCSW' },
//   { label: 'FNP', value: 'FNP' },
//   { label: 'RD', value: 'RD' },
//   { label: 'LMFT', value: 'LMFT' },
//   { label: 'LPC', value: 'LPC' },
//   { label: 'Ph.D.', value: 'Ph.D.' },
//   { label: 'Psy.D.', value: 'Psy.D.' },
//   { label: 'LMHC', value: 'LMHC' },
//   { label: 'LCPC', value: 'LCPC' },
//   { label: 'LICSW', value: 'LICSW' },
//   { label: 'LPCC', value: 'LPCC' },
//   { label: 'None', value: 'None' },
// ];

export const PROVIDER_TYPE_OPTIONS = [
  { value: 'PHYSICIAN', label: 'Physician' },
  { value: 'NURSE_PRACTITIONER', label: 'Nurse Practitioner' },
  { value: 'PHYSICIAN_ASSISTANT', label: 'Physician Assistant' },
  { value: 'THERAPIST', label: 'Therapist' },
  { value: 'COUNSELOR', label: 'Counselor' },
  { value: 'SOCIAL_WORKER', label: 'Social Worker' },
  { value: 'PSYCHOLOGIST', label: 'Psychologist' },
  { value: 'PSYCHIATRIST', label: 'Psychiatrist' },
  { value: 'PHARMACIST', label: 'Pharmacist' },
  { value: 'DIETITIAN', label: 'Dietitian' },
  { value: 'OTHER', label: 'Other' },
];
export const GENDER_OPTIONS = [
  { label: 'Male', value: 'MALE' },
  { label: 'Female', value: 'FEMALE' },
  { label: 'Other', value: 'OTHER' },
];
