// Register all component keys here — used by reducerManager, sagaManager, and useFlexCleanup
export const COMPONENT_KEYS = {
  MAIN_APP: "MAIN_APP",
  DASHBOARD: "DASHBOARD",
  AUTH:"AUTH",
  CODES: "CODES",
  CONDITIONS: "CONDITIONS",
  CARE_PLANS: "CARE_PLANS",
  EDUCATION: "EDUCATION",
  PAYERS: "PAYERS",
  ASSESSMENTS: "ASSESSMENTS",
  SUB_ORG_PROFILE: "SUB_ORG_PROFILE",
  PROVIDER_GROUP_LIST: "PROVIDER_GROUP_LIST",
  PROVIDER_GROUP_PROVIDERS: "PROVIDER_GROUP_PROVIDERS",
};
