// Granular loading keys — each API call can have its own loading flag

import { COMPONENT_KEYS } from './componentKeys';

// Naming: COMPONENT_ACTION (matches the component it belongs to)
export const LOADING_KEYS = {
  // Global
  GLOBAL: 'GLOBAL',

  // Dashboard
  DASHBOARD_GET_STATS: 'DASHBOARD_GET_STATS',
  DASHBOARD_GET_CHART: 'DASHBOARD_GET_CHART',

  //Auth
  AUTH_POST_LOGIN: 'AUTH_POST_LOGIN',
  AUTH_POST_LOGOUT: 'AUTH_POST_LOGOUT',
  AUTH_POST_FORGOT_PASSWORD: 'AUTH_POST_FORGOT_PASSWORD',
  AUTH_POST_SET_PASSWORD: 'AUTH_POST_SET_PASSWORD',
  AUTH_POST_RESET_PASSWORD: 'AUTH_POST_RESET_PASSWORD',

  // Codes
  CODES_GET_LIST: 'CODES_GET_LIST',
  CODES_POST_CREATE: 'CODES_POST_CREATE',
  CODES_PATCH_UPDATE: 'CODES_PATCH_UPDATE',
  CODES_PATCH_FAVORITE: 'CODES_PATCH_FAVORITE',
  CODES_PATCH_ARCHIVE: 'CODES_PATCH_ARCHIVE',
  CODES_POST_IMPORT: 'CODES_POST_IMPORT',
  CODES_GET_TEMPLATE: 'CODES_GET_TEMPLATE',

  // Conditions
  CONDITIONS_GET_LIST: 'CONDITIONS_GET_LIST',
  CONDITIONS_POST_CREATE: 'CONDITIONS_POST_CREATE',
  CONDITIONS_PATCH_UPDATE: 'CONDITIONS_PATCH_UPDATE',
  CONDITIONS_PATCH_FAVORITE: 'CONDITIONS_PATCH_FAVORITE',
  CONDITIONS_PATCH_ARCHIVE: 'CONDITIONS_PATCH_ARCHIVE',

  // Payers
  PAYERS_GET_LIST: 'PAYERS_GET_LIST',
  PAYERS_POST_CREATE: 'PAYERS_POST_CREATE',
  PAYERS_PATCH_UPDATE: 'PAYERS_PATCH_UPDATE',
  PAYERS_PATCH_STATUS: 'PAYERS_PATCH_STATUS',
  PAYERS_PATCH_FAVORITE: 'PAYERS_PATCH_FAVORITE',
  PAYERS_PATCH_ARCHIVE: 'PAYERS_PATCH_ARCHIVE',
  PAYERS_POST_IMPORT: 'PAYERS_POST_IMPORT',
  PAYERS_GET_TEMPLATE: 'PAYERS_GET_TEMPLATE',

  // Care Plans
  CARE_PLANS_GET_LIST: 'CARE_PLANS_GET_LIST',
  CARE_PLANS_PATCH_FAVORITE: 'CARE_PLANS_PATCH_FAVORITE',
  CARE_PLANS_PATCH_ARCHIVE: 'CARE_PLANS_PATCH_ARCHIVE',

  // Assessments
  ASSESSMENTS_GET_LIST: 'ASSESSMENTS_GET_LIST',
  ASSESSMENTS_PATCH_FAVORITE: 'ASSESSMENTS_PATCH_FAVORITE',
  ASSESSMENTS_PATCH_ARCHIVE: 'ASSESSMENTS_PATCH_ARCHIVE',

  // Education
  EDUCATION_GET_LIST: 'EDUCATION_GET_LIST',
  EDUCATION_POST_CREATE: 'EDUCATION_POST_CREATE',
  EDUCATION_PATCH_UPDATE: 'EDUCATION_PATCH_UPDATE',
  EDUCATION_PATCH_FAVORITE: 'EDUCATION_PATCH_FAVORITE',
  EDUCATION_PATCH_ARCHIVE: 'EDUCATION_PATCH_ARCHIVE',
  EDUCATION_GET_DOWNLOAD: 'EDUCATION_GET_DOWNLOAD',

  // Sub-Organization List
  SUB_ORG_LIST_GET_LIST: 'SUB_ORG_LIST_GET_LIST',
  SUB_ORG_LIST_POST_CREATE: 'SUB_ORG_LIST_POST_CREATE',
  SUB_ORG_LIST_PATCH_STATUS: 'SUB_ORG_LIST_PATCH_STATUS',
};

// Map loading keys to their owning component (for cleanup)
export const LOADING_KEY_OWNER = {
  [LOADING_KEYS.DASHBOARD_GET_STATS]: COMPONENT_KEYS.DASHBOARD,
  [LOADING_KEYS.DASHBOARD_GET_CHART]: COMPONENT_KEYS.DASHBOARD,
  [LOADING_KEYS.AUTH_POST_LOGIN]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_LOGOUT]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_FORGOT_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_SET_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_RESET_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.CODES_GET_LIST]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_POST_CREATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_UPDATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_FAVORITE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_ARCHIVE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_POST_IMPORT]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_GET_TEMPLATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CONDITIONS_GET_LIST]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.CONDITIONS_POST_CREATE]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.CONDITIONS_PATCH_UPDATE]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.CONDITIONS_PATCH_FAVORITE]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.CONDITIONS_PATCH_ARCHIVE]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.PAYERS_GET_LIST]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_POST_CREATE]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_PATCH_UPDATE]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_PATCH_STATUS]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_PATCH_FAVORITE]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_PATCH_ARCHIVE]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_POST_IMPORT]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.PAYERS_GET_TEMPLATE]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.CARE_PLANS_GET_LIST]: COMPONENT_KEYS.CARE_PLANS,
  [LOADING_KEYS.CARE_PLANS_PATCH_FAVORITE]: COMPONENT_KEYS.CARE_PLANS,
  [LOADING_KEYS.CARE_PLANS_PATCH_ARCHIVE]: COMPONENT_KEYS.CARE_PLANS,
  [LOADING_KEYS.ASSESSMENTS_GET_LIST]: COMPONENT_KEYS.ASSESSMENTS,
  [LOADING_KEYS.ASSESSMENTS_PATCH_FAVORITE]: COMPONENT_KEYS.ASSESSMENTS,
  [LOADING_KEYS.ASSESSMENTS_PATCH_ARCHIVE]: COMPONENT_KEYS.ASSESSMENTS,
  [LOADING_KEYS.EDUCATION_GET_LIST]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.EDUCATION_POST_CREATE]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.EDUCATION_PATCH_UPDATE]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.EDUCATION_PATCH_FAVORITE]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.EDUCATION_PATCH_ARCHIVE]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.EDUCATION_GET_DOWNLOAD]: COMPONENT_KEYS.EDUCATION,
  [LOADING_KEYS.SUB_ORG_LIST_GET_LIST]: COMPONENT_KEYS.SUB_ORG_LIST,
  [LOADING_KEYS.SUB_ORG_LIST_POST_CREATE]: COMPONENT_KEYS.SUB_ORG_LIST,
  [LOADING_KEYS.SUB_ORG_LIST_PATCH_STATUS]: COMPONENT_KEYS.SUB_ORG_LIST,
};
