// Granular loading keys — each API call can have its own loading flag

import { COMPONENT_KEYS } from './componentKeys';

// Naming: COMPONENT_ACTION (matches the component it belongs to)
export const LOADING_KEYS = {
  // Global
  GLOBAL: 'GLOBAL',

  // Dashboard
  DASHBOARD_GET_STATS: 'DASHBOARD_GET_STATS',
  DASHBOARD_GET_CHART: 'DASHBOARD_GET_CHART',

  //Auth
  AUTH_POST_LOGIN: 'AUTH_POST_LOGIN',
  AUTH_POST_LOGOUT: 'AUTH_POST_LOGOUT',
  AUTH_POST_FORGOT_PASSWORD: 'AUTH_POST_FORGOT_PASSWORD',
  AUTH_POST_SET_PASSWORD: 'AUTH_POST_SET_PASSWORD',
  AUTH_POST_RESET_PASSWORD: 'AUTH_POST_RESET_PASSWORD',

  // Codes
  CODES_GET_LIST: 'CODES_GET_LIST',
  CODES_POST_CREATE: 'CODES_POST_CREATE',
  CODES_PATCH_UPDATE: 'CODES_PATCH_UPDATE',
  CODES_PATCH_FAVORITE: 'CODES_PATCH_FAVORITE',
  CODES_PATCH_ARCHIVE: 'CODES_PATCH_ARCHIVE',
  CODES_POST_IMPORT: 'CODES_POST_IMPORT',
  CODES_GET_TEMPLATE: 'CODES_GET_TEMPLATE',

  // Conditions
  CONDITIONS_GET_LIST: 'CONDITIONS_GET_LIST',

  // Payers
  PAYERS_GET_LIST: 'PAYERS_GET_LIST',

  // Care Plans
  CARE_PLANS_GET_LIST: 'CARE_PLANS_GET_LIST',

  // Assessments
  ASSESSMENTS_GET_LIST: 'ASSESSMENTS_GET_LIST',

  // Education
  EDUCATION_GET_LIST: 'EDUCATION_GET_LIST',
};

// Map loading keys to their owning component (for cleanup)
export const LOADING_KEY_OWNER = {
  [LOADING_KEYS.DASHBOARD_GET_STATS]: COMPONENT_KEYS.DASHBOARD,
  [LOADING_KEYS.DASHBOARD_GET_CHART]: COMPONENT_KEYS.DASHBOARD,
  [LOADING_KEYS.AUTH_POST_LOGIN]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_LOGOUT]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_FORGOT_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_SET_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.AUTH_POST_RESET_PASSWORD]: COMPONENT_KEYS.AUTH,
  [LOADING_KEYS.CODES_GET_LIST]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_POST_CREATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_UPDATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_FAVORITE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_PATCH_ARCHIVE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_POST_IMPORT]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CODES_GET_TEMPLATE]: COMPONENT_KEYS.CODES,
  [LOADING_KEYS.CONDITIONS_GET_LIST]: COMPONENT_KEYS.CONDITIONS,
  [LOADING_KEYS.PAYERS_GET_LIST]: COMPONENT_KEYS.PAYERS,
  [LOADING_KEYS.CARE_PLANS_GET_LIST]: COMPONENT_KEYS.CARE_PLANS,
  [LOADING_KEYS.ASSESSMENTS_GET_LIST]: COMPONENT_KEYS.ASSESSMENTS,
  [LOADING_KEYS.EDUCATION_GET_LIST]: COMPONENT_KEYS.EDUCATION,
};
