export const FORM_FIELDS_NAMES = {
  SUB_ORG_NAME: 'subOrgName',
  COUNTRY_CODE: 'countryCode',
  CONTACT_NUMBER: 'contactNumber',
  EMAIL: 'email',
  WEBSITE: 'website',
  ADDRESS_LINE_1: 'addressLine1',
  ADDRESS_LINE_2: 'addressLine2',
  STATE: 'state',
  COUNTRY: 'country',
  CITY: 'city',
  ZIP_CODE: 'zipCode',
  COUNTY: 'county',
  IMPORT_SUB_ORG: 'importSubOrg',
  IMPORT_SUB_ORG_ADMIN: 'importSubOrgAdmin',
  ADMIN_CONTACTS: 'adminContacts',
  ADMIN_FIRST_NAME: 'firstName',
  ADMIN_LAST_NAME: 'lastName',
  ADMIN_EMAIL: 'email',
  ADMIN_PHONE: 'phone',
};
